name: Example of GitHub Environment Variables

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display GitHub environment variables
        run: |
          echo "Workflow triggered by: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Commit SHA: $GITHUB_SHA"
          echo "Branch or Tag: $GITHUB_REF"
          echo "Event Name: $GITHUB_EVENT_NAME"
          echo "Workflow Run ID: $GITHUB_RUN_ID"
